import { docs } from "collections/server";
import { loader } from "fumadocs-core/source";

// The Fumadocs source loader over the docs collection generated from
// content/docs. `.source` is generated by fumadocs-mdx on dev/build.
export const source = loader({
  baseUrl: "/docs",
  source: docs.toFumadocsSource(),
});
